version: '3.8'

services:
  db:
    build:
      context: ./postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@123
      POSTGRES_DB: Budgy_development
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: true
    command: sh -c "./bin/webpack-dev-server -b 0.0.0.0 -p 3035 & bundle exec rails server -b 0.0.0.0 -p 3000"
