apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-configmap
data:
  init.sh: |
    #!/bin/bash

    # Switch to the postgres user
    su - postgres <<EOF

    # Run psql and execute the command to create the database
    psql -c "CREATE DATABASE \"open-flights_development\";"

    EOF
