apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: csag095/rails-db-app-db:v1
          ports:
            - name: postgres-port
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: dbpassword
          volumeMounts:
          - name: postgres-config
            mountPath: /etc/postgresql/
      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config
