apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-sql
          image: postgres:14.12
          command:
            - /bin/sh
            - -c
            - |
              su -c 'psql -c "CREATE DATABASE \"open-flights_development\";"' - postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: dbpassword
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: postgres:14.12
          ports:
            - name: postgres-port
              containerPort: 5432
          env:
            - name: POSTGRES_SHARED_BUFFERS
              value: "256MB"
            - name: POSTGRES_MAX_CONNECTIONS
              value: "200"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: dbpassword
                  name: postgres-secret
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
