apiVersion: v1
kind: Service
metadata:
  name: rails-app-svc
spec:
  ports:
    - port: 3010
      targetPort: rails-app-port
      protocol: TCP
  selector:
    app: rails-app-dep
  type: LoadBalancer