apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.12
          ports:
            - name: postgres-port
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "admin@123"
          volumeMounts:
          - name: init-sql-volume
            mountPath: /docker-entrypoint-initdb.d/init.sql
            subPath: init.sql
      volumes:
        - name: init-sql-volume
          configMap:
            name: init-sql-configmap

