apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app-dep
  labels:
    app: rails-app-dep
spec:
  selector:
    matchLabels:
      app: rails-app-dep
  replicas: 1
  template:
    metadata:
      labels:
        app: rails-app-dep
    spec:
      containers:
        - name: rails-db-app-web
          image: csag095/rails-db-app-web:v4
          ports:
            - name: rails-app-port
              containerPort: 3000
          env:
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: dbpassword
