apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.12
          ports:
            - name: postgres-port
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "admin@123"
          volumeMounts:
            - name: init-sql-volume
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
          command: ["postgres"]
          args: ["-c", "host all all 0.0.0.0/0 trust"]
      volumes:
        - name: init-sql-volume
          configMap:
            name: init-sql-configmap
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
