apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app-dep
  labels:
    app: rails-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app-dep
  template:
    metadata:
      labels:
        app: rails-app-dep
    spec:
      containers:
        - name: rails-db-app-web
          image: csag095/rails-db-app-web:v5
          ports:
            - name: rails-app-port
              containerPort: 3000
          env:
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "admin@123"
