apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app-dep
  labels:
    app: rails-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app-dep
  template:
    metadata:
      labels:
        app: rails-app-dep
    spec:
      containers:
        - name: rails-db-app-web
          image: csag095/rails-db-app-web:v6
          ports:
            - name: rails-app-port
              containerPort: 3000
          env:
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: dbpassword
                  name: postgres-secret
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          command:
            - "/bin/bash"
            - "-c"
            - "/usr/bin/env -S ruby bin/rails db:migrate && bundle exec rails server -b 0.0.0.0"
