apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.12
          ports:
            - name: postgres-port
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "admin@123"
          command: ["postgres"]
          args: ["-c", "listen_addresses=*"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 999 # or the UID of the "postgres" user in the container
          volumeMounts:
            - name: init-sql-volume
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: init-sql-volume
          configMap:
            name: init-sql-configmap
