apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-tekton
  namespace: tekton-pipelines
spec:
  project: default

  source:
    repoURL: https://github.com/Sarang095/Tekton.git
    targetRevision: HEAD
    path: Tekton/
  destination:
    server: https://kubernetes.default.svc

  syncPolicy:

    automated:
      selfHeal: true
      prune: true
