apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application-tekton
  namespace: tekton-pipelines
spec:
  project: default

  source:
    repoURL: https://github.com/Sarang095/Rails-DB-APP.git
    targetRevision: HEAD
    path: tekton/
  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
