apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-role-binding
roleRef:
  kind: Role
  name: tekton-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: tekton-serviceaccount
