apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push
spec:
  description: |
    This pipeline clones a git repo, builds a Docker image with Kaniko and
    pushes it to a registry
  params:
    - name: repo-url
      type: string
    - name: image-reference
      type: string
    - name: registry-url
      type: string
  workspaces:
    - name: shared-data
    - name: dockerhub-secret
  tasks:  # Add the 'tasks' field here
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
    - name: build-push
      runAfter: ["fetch-source"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: dockerhub-secret
      params:
        - name: IMAGE
          value: $(params.image-reference)
        - name: DOCKER_REGISTRY
          value: $(params.registry-url)
