default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'admin@123') %>
  host: <%= ENV.fetch('POSTGRES_SERVICE_HOST', 'postgres.myapp.svc.cluster.local') %>
  port: <%= ENV.fetch('POSTGRES_SERVICE_PORT', 5432) %>
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  database: open-flights_development

test:
  <<: *default
  database: open-flights_test
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'admin@123') %>

production:
  <<: *default
  database: open-flights_production
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('OPEN-FLIGHTS_DATABASE_PASSWORD', 'admin@123') %>
